### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by quirinpa** [wkoszek/godaddycli#1]
Fresh install. I can't curl dns.godaddy.com either (cannot resolve host). Is this on me?
```
> godaddycli                    
Traceback (most recent call last):
  File "/usr/local/bin/godaddycli", line 11, in <module>
    load_entry_point('godaddycli==0.1.4', 'console_scripts', 'godaddycli')()
  File "/usr/local/lib/python2.7/site-packages/godaddycli/godaddycli.py", line 173, in main
    doit(cfg)
  File "/usr/local/lib/python2.7/site-packages/godaddycli/godaddycli.py", line 169, in doit
    return godaddycli(user, password, cfg)
  File "/usr/local/lib/python2.7/site-packages/godaddycli/godaddycli.py", line 90, in godaddycli
    c = client.login(username, password)
  File "/usr/local/lib/python2.7/site-packages/pygodaddy/client.py", line 99, in login
    r = self.session.get(self.default_url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dns.godaddy.com', port=443): Max retries exceeded with url: /default.aspx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1839f4270f50>: Failed to establish a new connection: [Errno -5] no address associated with name',))
```

**Comment by wkoszek** [comment]
@quirinpa Yes. I think someone else reported a similar issue to me. Since I've made `godaddycli` things have changed at GoDaddy, and nowadays I'm using my solution of Google Sheets + Ruby script fetching them at pushing to GoDaddy via API. Maybe I should just publish that instead.

**Comment by quirinpa** [comment]
@wkoszek I understand. Their website is crappy, it won't let me do anything, that's why I was looking for a different solution. Anyhow, I'll call their support line today.

All I want to do is point to Google Cloud Computing nameservers.

Well, see you around.

PS: Wait what? Ruby GoDaddy API? Ohhh I [see](https://github.com/nasskach/ruby-godaddy-api) it now. it's a rest service :P . I'll try to figure it out. Thanks!

**Comment by iokobi** [comment]
Experiencing same error. :(

**Comment by wkoszek** [comment]
@quirinpa @iokobi I just marked this project as broken. If you guys care, please submit patches. In the meantime I'm closing this issue.
